#!/bin/bash

#balabala


#globle var
menu_choice=""
current_cd=""
title_file="title.cdb"
tracks_file="tracks.cdb"
tmp_file=/tmp/cdb.$$
trap "rm -f $tmp_file" EXIT

#function
get_return(){
    echo -e "Press return \c"
    read x
    return 0
}

get_confirm()
{
    echo -e "Are you sure? \c"
    while true
    do
        read x
        case "$x" in
            y | yes | Y | Yes | YES)
                return 0;;
            n | no  | N | No  | NO)
                echo "Cancelled"
                return 1;;
            *)
                echo "Please enter yes or no";;
        esac
    done
}

set_menu_choice(){
    clear
    echo "Options :-"
    echo
    echo "  a) Add new CD"
    echo "  b) Find CD"
    echo "  c) Count the CDs and tracks in the catalog"
    if [ "$cdcatnum" != "" ]
    then
        echo "  l) List tracks on $cdtitle"
        echo "  r) Remove $cdtitle"
        echo "  u) Update track information for $cdtitle"
    fi
    echo "  q) Quit"
    echo 
    echo -e "Please enter choice then press return \c"
    read menu_choice
    return    
}


insert_title(){
    echo $* >> $title_file
    return
}

insert_track(){
    echo $* >> $tracks_fild
    return
}

add_record_tracks(){
    echo "Enter track information for this CD"
    echo "When no more tracks enter q"
    cdtrack=1
    cdtitle=""
    while [ "$cdtitle" != "q" ]
    do
        echo -e "Track $cdtrack, track title? \c"
        read tmp
        # don't include ,
        cdtitle=${tmp%%,*}   #enter  title,abcd, cdtitle= title
        if [ "$tmp" != "$cdtitle" ]
        then
            echo "Sorry, no commas allowed"  #no ,  on the title
            continue
        fi

        # is null?
        if [ -n $cdtitle ] ;then
            if [ "$cdtitle" != "q" ]; then
                insert_track $cdcatnum, $cdtrack, $cdtitle
            fi
        else
            cdtrack=$((cdtrack-1))
        fi
        cdtrack=$((cdtrack+1))
    done
}

add_records(){ 
    # Prompt for the  init information
    echo -e "Enter catalog name \c"
    read tmp
    cdcatnum=${tmp%%,*}
    
    echo -e "Enter title \c"
    read tmp
    cdtitle=${tmp%%,*}
    
    echo -e "Enter type \c"
    read tmp
    cdtype=${tmp%%,*}

    echo -e "Enter artist/composer \c"
    read tmp
    cdac=${tmp%%,*}

    echo About to add new entry
    echo "$cdcatnum $cdtitle $cdtype $cdac"
    
    if get_confirm ; then
        insert_title $cdcatnum,$cdtitle,$cdtype,$cdac
        add_record_tracks
    else
        remove_records
    fi
    
    return
}






