#!/bin/bash
set -x
set -e

#Ask some question

#function start
confirmAnswer() {
echo "$?"
if [ $? != 0 ]; then
    echo "aaa"
    dialog --infobox "Thank you anyway" 9 18
    sleep 2
    dialog --clear
    exit 0
fi
}
#function end

dialog --title "Question" --msgbox "Welcome to my simple survice" 9 18

dialog --title "Confirm" --yesno "Are you willing to take part ?" 9 18
echo "$?"
confirmAnswer

dialog --title "Question" --inputbox "Please enter you name" 9 18  2>_1.txt
Q_name=$(cat _1.txt)

dialog --menu "$Q_name, what music do you list best?" 15 30 4 1 "Classical" 2 "Jaxx" 3 "Country" 4 "Other" 2>_1.txt
Q_music=$(cat _1.txt)

if [ "$Q_music" = "1" ];then
    dialog --title "Likes Classical" --msgbox "Good Choice" 12 25
else
    dialog --title "Likes $Q_music" --msgbox "Shame" 12 25
fi

sleep 2
dialog --clear
exit 0


