#!/bin/bash
set -e
set -x

unset foo
echo "${foo-hehe}"

foo=fud
echo "${foo-haha}"

foo=/usr/bin/X11/startx
echo "${foo#*/}"
echo "${foo##*/}"

bar=/usr/local/etc/local/networks
echo "${bar%local*}"
echo "${bar%%local*}"

exit 0

